/**
 * Destination name → HotelAPI CityCode mapping
 * These are the CORRECT HotelAPI REST API city codes (HotelAPIHolidays_HotelAPI).
 * Only cities with CONFIRMED hotel + flight availability are included.
 */
module.exports = {
    'reykjavik': { "cityCode": "135090", "cityName": "Reykjavik", "country": "IS" },
    'tallinn': { "cityCode": "140287", "cityName": "Tallinn", "country": "EE" },
    'bergen': { "cityCode": "111457", "cityName": "Bergen", "country": "NO" },
    'helsinki': { "cityCode": "120663", "cityName": "Helsinki", "country": "FI" },
    'prague': { "cityCode": "131864", "cityName": "Prague", "country": "CZ" },
    'istanbul': { "cityCode": "122727", "cityName": "Istanbul", "country": "TR" },
    'tromsø': { "cityCode": "133313", "cityName": "Tromsø", "country": "NO" },
    'santorini': { "cityCode": "314760", "cityName": "Santorini", "country": "GR" },
    'amsterdam': { "cityCode": "100851", "cityName": "Amsterdam", "country": "NL" },
    'vienna': { "cityCode": "141820", "cityName": "Vienna", "country": "AT" },
    'budapest': { "cityCode": "113506", "cityName": "Budapest", "country": "HU" },
    'lisbon': { "cityCode": "126668", "cityName": "Lisbon", "country": "PT" },
    'copenhagen': { "cityCode": "115633", "cityName": "Copenhagen", "country": "DK" },
    'dubrovnik': { "cityCode": "116855", "cityName": "Dubrovnik", "country": "HR" },
    'athens': { "cityCode": "108078", "cityName": "Athens", "country": "GR" },
    'edinburgh': { "cityCode": "117413", "cityName": "Edinburgh", "country": "GB" },
    'barcelona': { "cityCode": "110439", "cityName": "Barcelona", "country": "ES" },
    'rome': { "cityCode": "135419", "cityName": "Rome", "country": "IT" },
    'paris': { "cityCode": "130628", "cityName": "Paris", "country": "FR" },
    'london': { "cityCode": "125771", "cityName": "London", "country": "GB" },
    'nice': { "cityCode": "129615", "cityName": "Nice", "country": "FR" },
    'madrid': { "cityCode": "127200", "cityName": "Madrid", "country": "ES" },
    'venice': { "cityCode": "141728", "cityName": "Venice", "country": "IT" },
    'milan': { "cityCode": "128453", "cityName": "Milan", "country": "IT" },
    'malaga': { "cityCode": "127413", "cityName": "Malaga", "country": "ES" },
    'lyon': { "cityCode": "126957", "cityName": "Lyon", "country": "FR" },
    'bordeaux': { "cityCode": "112303", "cityName": "Bordeaux", "country": "FR" },
    'valletta': { "cityCode": "141652", "cityName": "Valletta", "country": "MT" },
    'thessaloniki': { "cityCode": "140627", "cityName": "Thessaloniki", "country": "GR" },
    'glasgow': { "cityCode": "119718", "cityName": "Glasgow", "country": "GB" },
    'stockholm': { "cityCode": "139072", "cityName": "Stockholm", "country": "SE" },
    'oslo': { "cityCode": "130259", "cityName": "Oslo", "country": "NO" },
    'berlin': { "cityCode": "111410", "cityName": "Berlin", "country": "DE" },
    'geneva': { "cityCode": "119412", "cityName": "Geneva", "country": "CH" },
    'brussels': { "cityCode": "113279", "cityName": "Brussels", "country": "BE" },
    'krakow': { "cityCode": "124781", "cityName": "Krakow", "country": "PL" },
    'warsaw': { "cityCode": "142081", "cityName": "Warsaw", "country": "PL" },
    'split': { "cityCode": "138951", "cityName": "Split", "country": "HR" },
    'riga': { "cityCode": "135170", "cityName": "Riga", "country": "LV" },
    'vilnius': { "cityCode": "142095", "cityName": "Vilnius", "country": "LT" },
    'bucharest': { "cityCode": "113113", "cityName": "Bucharest", "country": "RO" },
    'sofia': { "cityCode": "138812", "cityName": "Sofia", "country": "BG" },
    'ljubljana': { "cityCode": "126539", "cityName": "Ljubljana", "country": "SI" },
    // ── New HotelAPI-verified cities ──
    'dublin': { "cityCode": "116780", "cityName": "Dublin", "country": "IE" },
    'manchester': { "cityCode": "127582", "cityName": "Manchester", "country": "GB" },
    'antalya': { "cityCode": "108173", "cityName": "Antalya", "country": "TR" },
    'izmir': { "cityCode": "122973", "cityName": "Izmir", "country": "TR" },
    'corfu': { "cityCode": "115295", "cityName": "Corfu", "country": "GR" },
    'rhodes': { "cityCode": "135192", "cityName": "Rhodes", "country": "GR" },
    'mykonos': { "cityCode": "129106", "cityName": "Mykonos", "country": "GR" },
    'chania': { "cityCode": "114501", "cityName": "Chania", "country": "GR" },
    'palma': { "cityCode": "130462", "cityName": "Palma", "country": "ES" },
    'tenerife': { "cityCode": "140401", "cityName": "Tenerife", "country": "ES" },
    'faro': { "cityCode": "118560", "cityName": "Faro", "country": "PT" },
    'marseille': { "cityCode": "127791", "cityName": "Marseille", "country": "FR" },
    'toulouse': { "cityCode": "140913", "cityName": "Toulouse", "country": "FR" },
    'frankfurt': { "cityCode": "118921", "cityName": "Frankfurt", "country": "DE" },
    'dusseldorf': { "cityCode": "116908", "cityName": "Dusseldorf", "country": "DE" },
    'cologne': { "cityCode": "115104", "cityName": "Cologne", "country": "DE" },
    'pisa': { "cityCode": "131321", "cityName": "Pisa", "country": "IT" },
    'verona': { "cityCode": "141845", "cityName": "Verona", "country": "IT" },
    'palermo': { "cityCode": "130427", "cityName": "Palermo", "country": "IT" },
    'catania': { "cityCode": "114362", "cityName": "Catania", "country": "IT" },
    'bari': { "cityCode": "110350", "cityName": "Bari", "country": "IT" },
    'wroclaw': { "cityCode": "142553", "cityName": "Wroclaw", "country": "PL" },
    'zagreb': { "cityCode": "142789", "cityName": "Zagreb", "country": "HR" },
    'belgrade': { "cityCode": "111240", "cityName": "Belgrade", "country": "RS" },
    'tirana': { "cityCode": "140729", "cityName": "Tirana", "country": "AL" },
    'larnaca': { "cityCode": "125443", "cityName": "Larnaca", "country": "CY" },
    'paphos': { "cityCode": "130491", "cityName": "Paphos", "country": "CY" },
    'cork': { "cityCode": "115373", "cityName": "Cork", "country": "IE" },
    'varna': { "cityCode": "141659", "cityName": "Varna", "country": "BG" },
    'clujnapoca': { "cityCode": "114972", "cityName": "Cluj-Napoca", "country": "RO" },
    'sarajevo': { "cityCode": "137252", "cityName": "Sarajevo", "country": "BA" },
};
